config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "user", path_names: {
    sign_in:      'login',
    sign_out:     'logout',
    password:     'secret',
    confirmation: 'verification',
    unlock:       'unblock',
    registration: 'register',
    sign_up:      'registration'
  }

  namespace :website do
    get 'index'
  end

  get    'apartment/new'        => 'apartment#new',    as: :apartment_new
  get    'apartment/list'       => 'apartment#list',   as: :apartment_list
  post   'apartment/create'     => 'apartment#create', as: :apartment_create
  get    'apartment/:id'        => 'apartment#show',   as: :apartment_show
  get    'apartment/edit/:id'   => 'apartment#edit',   as: :apartment_edit
  put    'apartment/update/:id' => 'apartment#update', as: :apartment_update
  delete 'apartment/delete/:id' => 'apartment#delete', as: :apartment_delete

  get 'profile' => 'user#index', as: :profile

  root 'website#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :user

  mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apartments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/apartment_controller.rb
class ApartmentController < ApplicationController
  before_action :authenticate_user!, except: [:list, :show]

  def new
    @apartment = Apartment.new
  end

  def create
    current_user.apartments.create params['apartment'].permit!
    redirect_to controller: 'user', action: 'index'
  end

  def delete
    Apartment.find(params[:id]).delete
    redirect_to controller: 'user', action: 'index'
  end

  def update
    apartment = Apartment.find(params[:id])
    apartment.update params['apartment'].permit!
    redirect_to controller: 'user', action: 'index'
  end

  def list
    sw = params['coords']['sw']
    ne = params['coords']['ne']
    apartments = Apartment.where('lat BETWEEN ? AND ? AND lng BETWEEN ? AND ? ',
                                  sw['lat'], ne['lat'], sw['lng'], ne['lng'])

    render partial: 'partials/apartments', locals: { apartments: apartments }
  end

  def show
    @apartment = Apartment.find(params[:id])
  end

  def edit
    @apartment = Apartment.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @apartments = current_user.apartments
  end
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @apartments = Apartment.all
  end
end

app/helpers/apartment_helper.rb
module ApartmentHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/apartment/edit.slim
.apartment-form
  script src="http://maps.googleapis.com/maps/api/js?sensor=false&callback=latlng_init"
  h1 Edit appartment

  = form_for(@apartment, as: :apartment, url: apartment_update_path(@apartment), html: { method: :put }) do |f|
    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :title, "Title"
        = f.text_field :title, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :description, "Descriprion"
        = f.text_area :description, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :price, "Price"
        = f.text_field :price, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :options, "Options"
        = f.text_field :options, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :address, "Address"
        = f.text_field :address, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :picture, "Picture"
        = f.file_field :picture, class: "apartment-form__picture-input"

    .row
      .col-xs-12
        .apartment-form__hint Move the marker, or double click on the map.
        .gllpLatlonPicker
          .apartment-form__map.gllpMap Google Maps
          = f.hidden_field :lat, class: "gllpLatitude"
          = f.hidden_field :lng, class: "gllpLongitude"
    .row.apartment-form__fieldset
      .col-xs-12
        = f.submit :update, class: 'btn btn-success'

app/views/apartment/new.slim
script src="http://maps.googleapis.com/maps/api/js?sensor=false&callback=latlng_init"
.apartment-form
  h1 Add appartment

  = form_for(@apartment, as: :apartment, url: apartment_create_path(@apartment), html: { method: :post }) do |f|
    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :title, "Title"
        = f.text_field :title, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :description, "Descriprion"
        = f.text_area :description, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :price, "Price"
        = f.text_field :price, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :options, "Options"
        = f.text_field :options, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :address, "Address"
        = f.text_field :address, class: "apartment-form__input"

    .row.apartment-form__fieldset
      .col-xs-12
        = f.label :picture, "Picture"
        = f.file_field :picture, class: "apartment-form__picture-input"

    .row
      .col-xs-12
        .apartment-form__hint Move the marker, or double click on the map.
        .gllpLatlonPicker
          .apartment-form__map.gllpMap Google Maps
          = f.hidden_field :lat, class: "gllpLatitude"
          = f.hidden_field :lng, class: "gllpLongitude"
    .row.apartment-form__fieldset
      .col-xs-12
        = f.submit :create, class: 'btn btn-success'

app/views/apartment/show.slim
h1
  .col-sm-6.col-xs-12
    = @apartment.title unless @apartment.title.blank?
  .col-sm-6.col-xs-12.apartment__contact
    = ('Contact: ' + mail_to(@apartment.user.email)).html_safe

.row
  .col-xs-12
    .row
      .col-md-6.col-xs-12
        .apartment__picture= image_tag @apartment.picture.url unless @apartment.picture.blank?
      .col-md-4.col-xs-12
        h6.apartment__address= @apartment.address unless @apartment.address.blank?
        .apartment__description= @apartment.description unless @apartment.description.blank?
        .apartment__options= @apartment.options unless @apartment.options.blank?

      .col-md-2.col-xs-12
        .apartment__price= 'Price: ' + @apartment.price.to_s unless @apartment.price.blank?

app/views/layouts/application.slim
doctype html
html
  head
    title TestApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .layout__header
      .container
        .row
          = link_to 'Home', root_path
          - if user_signed_in?
            = link_to 'Logout', destroy_user_session_path, method: :delete
            = link_to 'Profile', profile_path
          - else
            = link_to 'Sign in', new_user_session_path
            = link_to 'Sign up', new_user_registration_path
    .container
      .row
        = yield
        .clearfix
    .layout__footer
      .container
        .row
          = link_to 'Home', root_path
          - if user_signed_in?
            = link_to 'Logout', destroy_user_session_path, method: :delete
            = link_to 'Profile', profile_path
          - else
            = link_to 'Sign in', new_user_session_path
            = link_to 'Sign up', new_user_registration_path

app/views/partials/_apartments.slim
.apartment__list
  - if apartments.blank?
    h2 There are no propositions in this area
  - else
    - apartments.each do |a|
      = link_to apartment_show_path(a) do
        .row
          .col-xs-12
            h2= a.title unless a.title.blank?
            .row
              .col-md-2.col-xs-12
                .apartment__picture= image_tag a.picture.url(:thumb) unless a.picture.blank?
              .col-md-7.col-xs-12
                h6.apartment__address= a.address unless a.address.blank?
                .apartment__description= a.description unless a.description.blank?
                .apartment__options= a.options unless a.options.blank?
              .col-md-3.col-xs-12
                .apartment__price= a.price unless a.price.blank?

app/views/user/index.slim
h1.profile__title Profile
h2.profile__name= current_user.name

.profile__new
  = link_to "Add proposition", apartment_new_path, class: 'btn btn-primary'

- @apartments.each do |a|
  .row
    .col-xs-12
      h2= a.title unless a.title.blank?
      .row
        .col-md-2.col-xs-12
          .apartment__picture= image_tag a.picture.url(:thumb) unless a.picture.blank?
        .col-md-5.col-xs-12
          h6.apartment__address= a.address unless a.address.blank?
          .apartment__description= a.description unless a.description.blank?
          .apartment__options= a.options unless a.options.blank?
        .col-md-3.col-xs-12
          .apartment__price= a.price unless a.price.blank?
        .col-md-2.col-xs-12
          = link_to 'Edit',   apartment_edit_path(a), class: 'btn btn-primary'
          = link_to 'Delete', apartment_delete_path(a), method: :delete, class: 'btn btn-danger'

app/views/website/index.slim
.col-sm-6.col-xs-12
  .apartment__list-map#map
  script type="text/javascript"
    | function changeList (b) {
    |   coords = { sw: { lat: b.getSouthWest().lat(), lng: b.getSouthWest().lng() },
    |              ne: { lat: b.getNorthEast().lat(), lng: b.getNorthEast().lng() } };
    |   $.get( "#{apartment_list_path}", { coords: coords }).done(function( data ) {
    |     $('.apartment__list').html(data);
    |   });
    | }

    | function initMap() {
    |   var map = new google.maps.Map(document.getElementById('map'), {
    |     center: { lat: 51.506594, lng: -0.127223 },
    |     scrollwheel: true,
    |     zoom: 11,
    |     styles: [
    |         {
    |           featureType: "transit.station",
    |           stylers: [
    |             { visibility: "off" }
    |           ]
    |         }
    |       ]
    |   });

    | google.maps.event.addListener(map, 'dragend', function() {
    |   changeList(map.getBounds());
    | });

    | google.maps.event.addListener(map, 'zoom_changed', function() {
    |   changeList(map.getBounds());
    | });

    | google.maps.event.addListener(map, 'idle', function() {
    |   changeList(map.getBounds());
    | });

    - @apartments.each do |a|
      | var marker#{a.id} = new google.maps.Marker({
      |   position: {lat: #{a.lat}, lng: #{a.lng} },
      |   animation: google.maps.Animation.DROP,
      |   map: map
      | });

      | var infowindow#{a.id} = new google.maps.InfoWindow({
      |   content: '<a href="#{apartment_show_path(a)}"><div><b>#{a.title.truncate(30)}</b></div><img src="#{a.picture.url(:map_thumb)}"></a>'
      | });

      | marker#{a.id}.addListener('click', function() {
      |   infowindow#{a.id}.open(map, marker#{a.id});
      | });

    | }


  script async="" defer="" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWaTwAZoBlzmzTzRnQ6HeruMkreEP9ThU&callback=initMap"

.col-sm-6.col-xs-12.apartment__list
  h3 Loading...